name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker image tag
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u deepuprajapat --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -f Dockerfile \
            -t ghcr.io/deepuprajapat/im-backend:${{ env.TAG }} \
            -t ghcr.io/deepuprajapat/im-backend:latest \
            .

      - name: Push Docker image (tag + latest)
        run: |
          docker push ghcr.io/deepuprajapat/im-backend:${{ env.TAG }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE_TAG=${{ env.TAG }}
            echo "Deploying IM Backend with image tag: $IMAGE_TAG"
            echo "${{ secrets.GHCR_PAT }}" | sudo docker login ghcr.io -u deepuprajapat --password-stdin

            cd ~/IM-Server/IM-Backend || exit 1

            # Create .env file with AWS secrets
            cat <<EOF > .env
            IMAGE_TAG=$IMAGE_TAG
            AWSACCESSKEY=${{ secrets.AWSACCESSKEY }}
            AWSSECRETKEY=${{ secrets.AWSSECRETKEY }}
            AWSREGION=${{ secrets.AWSREGION }}
            AWSBUCKET=${{ secrets.AWSBUCKET }} 
            EOF

            # Redeploy using Docker Compose
            sudo docker compose down
            sudo docker compose up -d --pull always --force-recreate

