name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker image tag
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u deepuprajapat --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            --build-arg AWSACCESSKEY=${{ secrets.AWSACCESSKEY }} \
            --build-arg AWSSECRETKEY=${{ secrets.AWSSECRETKEY }} \
            --build-arg AWSREGION=${{ secrets.AWSREGION }} \
            --build-arg AWSBUCKET=${{ secrets.AWSBUCKET }} \
            -f Dockerfile \
            -t ghcr.io/deepuprajapat/im-backend:${{ env.TAG }} \
            -t ghcr.io/deepuprajapat/im-backend:latest .

      - name: Push Docker image (tag + latest)
        run: |
          docker push ghcr.io/deepuprajapat/im-backend:${{ env.TAG }}
